"""Constants for the GWM China integration."""
from __future__ import annotations

# 集成 domain 与版本
DOMAIN = "gwm_cn"
VERSION = "0.2.3"

# 数据更新间隔(秒)。CN 网关有华为云 WAF,过于频繁可能被拦,先取 60s
UPDATE_INTERVAL = 60

# CN 网关与 API 路径
BASE_URL = "https://apgdm.gwmcloudcn.com"
GET_STATUS_PATH = "/mabdm/app-bff-vehicle/app-api/api/v2.0/vehicle/getLastStatus"

# 默认车型
DEFAULT_MODEL = "Tank 300"

# 配置流程字段
CONF_ACCESS_TOKEN = "access_token"
CONF_HW_WAF_SES_ID = "hw_waf_ses_id"
CONF_HW_WAF_SES_TIME = "hw_waf_ses_time"
CONF_VIN = "vin"
CONF_MODEL = "model"

# v0.2.0 新增:短信登录 + 远控
CONF_PHONE = "phone"
CONF_AUTH_STATE = "auth_state"
CONF_ENABLE_REMOTE = "enable_remote"
CONF_POLL_INTERVAL = "poll_interval"
DEFAULT_POLL_INTERVAL = 60
MIN_POLL_INTERVAL = 30
MAX_POLL_INTERVAL = 3600

# 远控命令(BeanTech T5 controlType,均来自 ha-gwm-ev 对官方 APP 的逆向实测)
CMD_VEHICLE_LOCK = "VEHICLE_LOCK"
CMD_VEHICLE_UNLOCK = "VEHICLE_UNLOCK"
CMD_WINDOW_CLOSE = "WINDOW_CLOSE"
CMD_WHISTLE = "WHISTLE"
CMD_FLASH = "FLASH"
CMD_WHISTLE_FLASH = "WHISTLE_FLASH"
CMD_ENGINE_START = "ENGINE_START"
CMD_ENGINE_STOP = "ENGINE_STOP"
CMD_SKYLIGHT_CLOSE = "SKYLIGNT_CLOSE"  # 官方 APP 拼写即如此,勿"修复"
CMD_AIR_CONDITIONER_START = "AIR_CONDITIONER_START"
CMD_AIR_CONDITIONER_STOP = "AIR_CONDITIONER_STOP"
CMD_DEFROST_FRONT_START = "DEFROST_FRONT_START"
CMD_DEFROST_FRONT_STOP = "DEFROST_FRONT_STOP"
CMD_DEFROST_BACK_START = "DEFROST_BACK_START"
CMD_DEFROST_BACK_STOP = "DEFROST_BACK_STOP"
CMD_STEERING_WHEEL_HEATING = "STEERING_WHEEL_HEATING"
CMD_STEERING_WHEEL_HEATLESS = "STEERING_WHEEL_HEATLESS"
CMD_SEAT_HEATING_START = "SEAT_HEATING_START"
CMD_SEAT_HEATING_STOP = "SEAT_HEATING_STOP"
CMD_SEAT_VENTILATION_START = "SEAT_VENTILATION_START"
CMD_SEAT_VENTILATION_STOP = "SEAT_VENTILATION_STOP"

# 远程空调范围(官方 APP 允许 17-31℃ 整数)
AC_MIN_TEMP = 17
AC_MAX_TEMP = 31
AC_DEFAULT_TEMP = 24
AC_DEFAULT_DURATION_SECONDS = 15 * 60

# 实体图片(device_tracker 显示集成 logo)
ENTITY_PICTURE_URL = "/gwm_cn/icon.png"

# 服务
SERVICE_REFRESH = "refresh"

# 设备属性键
ATTR_VIN = "vin"
ATTR_MODEL = "model"
ATTR_LATITUDE = "latitude"
ATTR_LONGITUDE = "longitude"
ATTR_UPDATE_TIME = "update_time"
ATTR_VEHICLE_NUMBER = "vehicle_number"
